### 数据预处理
- 创建一个人工数据集， 并存储在csv(逗号分隔值)文件中

In [3]:
import os

os.makedirs('data', exist_ok=True)
data_file = os.path.join('data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n')  # 列名
    f.write('NA,Pave,127500\n')  # 每行表示一个数据样本
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

- 从创建的csv文件中加载原始数据集

In [6]:
import pandas as pd

data = pd.read_csv(data_file)
print(data)
data

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000


NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000

- 为了处理缺失的数据，典型的方法包括 **插值** 和 **删除** ， 这里我们考虑插值

In [10]:
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2]
inputs = inputs.fillna(inputs.mean())
print(data.mean())
inputs

NumRooms         3.0
Price       137900.0
dtype: float64


NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN

- 对于`inputs`中的类别值或者离散值，我们可以**将NAN视为一个类别**

In [11]:
inputs = pd.get_dummies(inputs, dummy_na=True)
inputs

NumRooms  Alley_Pave  Alley_nan
0       3.0           1          0
1       2.0           0          1
2       4.0           0          1
3       3.0           0          1

- 现在inputs 和 outputs 都是数值类型，可以把他们转化成张量

In [13]:
import torch

'''深度学习中一般用float32浮点数'''
X, y = torch.tensor(inputs.values, dtype=torch.float32), torch.tensor(outputs.values)
X, y

(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]]),
 tensor([127500, 106000, 178100, 140000]))

- reshape和view的区别
  - 区别在于被操作的那个tensor是否是连续的，当连续时两者一致，当不连续时reshape会返回新的tensor，该tensor与原来的再无关联，修改reshape返回的tensor不会变更原来的

In [24]:
# 李沐老师例子
a = torch.arange(12)
b = a.reshape((3,4))
b[:] = 2
a

tensor([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [21]:
a = torch.rand((3, 3))
b = a.permute(1,0)
print(a)
print(b)
c = b.reshape(9)
print(c)
c[0] = 10 #这里观察一下a,b对应位置的数值
print(c)
print(a)
print(b)

tensor([[0.0050, 0.0123, 0.3050],
        [0.8006, 0.9626, 0.8154],
        [0.7447, 0.4563, 0.6295]])
tensor([[0.0050, 0.8006, 0.7447],
        [0.0123, 0.9626, 0.4563],
        [0.3050, 0.8154, 0.6295]])
tensor([0.0050, 0.8006, 0.7447, 0.0123, 0.9626, 0.4563, 0.3050, 0.8154, 0.6295])
tensor([10.0000,  0.8006,  0.7447,  0.0123,  0.9626,  0.4563,  0.3050,  0.8154,
         0.6295])
tensor([[0.0050, 0.0123, 0.3050],
        [0.8006, 0.9626, 0.8154],
        [0.7447, 0.4563, 0.6295]])
tensor([[0.0050, 0.8006, 0.7447],
        [0.0123, 0.9626, 0.4563],
        [0.3050, 0.8154, 0.6295]])
