### 线性代数
1. 向量的点积
   - $a^{T}b = \sum_{i} {a_ib_i}$
   - 正交向量$a^Tb=0$
2. 矩阵乘法
   1. 矩阵乘以向量
    $$c = A \times b \space \text{where}\space c_i = \sum_{j}{A_{ij}b_{j}}$$ 
    **注**：矩阵的乘法可以理解为空间的扭曲，一个向量和一个矩阵相乘变成了另外一个向量之后，可以理解为对其空间进行了扭曲
    2. 矩阵乘以矩阵
    $$C = AB \space \space where \space C_{ik} = \sum_{j}{A_{ij}B_{jk}}$$
3. 范数
$$c = A \cdot b \space   hence \space \|\mathbf{c}\| \leq \|A\| \cdot \|b\|$$
   1. 常见范数
      - **矩阵范数**，最小的满足上面公式的值
      - **Frobenius**范数$\|A\|_{Frob} = \sqrt{\sum{A_{ij}^{2}}}$
4. 对称矩阵和反对称矩阵
$$A_{ij} = A_{ji} \space and \space A_{ij} = -A_{ji}$$
5. 正定矩阵
$$\|x\|^{2} = x^Tx \geq 0 \space \text{generalizes to} \space x^TAx \geq 0$$
6. 特征向量和特征值 - **不被矩阵改变方向的向量**,如下，向量x的方向没有呗改变
$$Ax = \lambda x$$

## 线性代数
- 标量由只有一个元素的张量表示

In [131]:
import torch

x = torch.tensor([3.0])
y = torch.tensor([2.0])

x + y, x * y, x / y, x ** y

(tensor([5.]), tensor([6.]), tensor([1.5000]), tensor([9.]))

- 可以将向量视为标量值组成的列表

In [132]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

- 向量长度

In [133]:
len(x)

4

- 指定两个分量 m 和 n来创建一个形状为$m \times n$的矩阵

In [134]:
A = torch.arange(20).reshape((5, 4))
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

- 矩阵的转置

In [135]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

- 对称矩阵A等于其转置：$A = A^{T}$

In [136]:
B = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [137]:
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

- 就像向量是标量的推广，矩阵是向量的推广，我们可以构建具有更多轴的数据结构

In [138]:
X = torch.arange(24).reshape((2, 3, 4))
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

- 给定具有相同形状的任何两个张量，任何按照元素的二元运算的结果都将是相同形状的张量

In [139]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone()  # 深拷贝
A, A + B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

- 两个矩阵按照元素乘法，称为 **哈达玛积**

In [140]:
A * B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [141]:
a = 2
X = torch.arange(24).reshape(2, 3, 4)
a + X, (a * X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

- 计算矩阵元素的和

In [142]:
x = torch.arange(4, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

- 表示任意形状张量的元素的和

In [143]:
A = torch.arange(20 * 2, dtype=torch.float32).reshape((2, 5, 4))
A.shape, A.sum(), A

(torch.Size([2, 5, 4]),
 tensor(780.),
 tensor([[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.],
          [16., 17., 18., 19.]],
 
         [[20., 21., 22., 23.],
          [24., 25., 26., 27.],
          [28., 29., 30., 31.],
          [32., 33., 34., 35.],
          [36., 37., 38., 39.]]]))

- 指定维度求和

In [144]:
# 按照第0维求和就相当于把两个5x4的矩阵的对应位置的元素加起来了
A_sum_axis0 = A.sum(dim=0)
A_sum_axis0, A_sum_axis0.shape

(tensor([[20., 22., 24., 26.],
         [28., 30., 32., 34.],
         [36., 38., 40., 42.],
         [44., 46., 48., 50.],
         [52., 54., 56., 58.]]),
 torch.Size([5, 4]))

In [145]:
# 第1维度求和相当于是按行求和，就是在行的层面上把数字加起来，操作就是对一列的数字求和
A_sum_axis1 = A.sum(dim=1)
A_sum_axis1, A_sum_axis1.shape

(tensor([[ 40.,  45.,  50.,  55.],
         [140., 145., 150., 155.]]),
 torch.Size([2, 4]))

In [146]:
A.sum(dim=[0, 1, 2]) # Same as `A.sum()`

tensor(780.)

- 矩阵的平均值

In [147]:
A.mean(), A.sum()/ A.numel()

(tensor(19.5000), tensor(19.5000))

In [148]:
A.mean(dim=0) == A.sum(dim=0) / A.shape[0]

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

- 计算综合或者均值的时候保持轴数不变， **利于后续做广播**

In [149]:
sum_A = A.sum(dim=1, keepdim=True)
sum_A

tensor([[[ 40.,  45.,  50.,  55.]],

        [[140., 145., 150., 155.]]])

- 通过广播将`A`除以`sum_A`

In [150]:
A / sum_A

tensor([[[0.0000, 0.0222, 0.0400, 0.0545],
         [0.1000, 0.1111, 0.1200, 0.1273],
         [0.2000, 0.2000, 0.2000, 0.2000],
         [0.3000, 0.2889, 0.2800, 0.2727],
         [0.4000, 0.3778, 0.3600, 0.3455]],

        [[0.1429, 0.1448, 0.1467, 0.1484],
         [0.1714, 0.1724, 0.1733, 0.1742],
         [0.2000, 0.2000, 0.2000, 0.2000],
         [0.2286, 0.2276, 0.2267, 0.2258],
         [0.2571, 0.2552, 0.2533, 0.2516]]])

- 某个轴计算A元素的累计总和， `cumulate_sum`

In [151]:
print(A)
A.cumsum(dim=1)

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]],

        [[20., 21., 22., 23.],
         [24., 25., 26., 27.],
         [28., 29., 30., 31.],
         [32., 33., 34., 35.],
         [36., 37., 38., 39.]]])


tensor([[[  0.,   1.,   2.,   3.],
         [  4.,   6.,   8.,  10.],
         [ 12.,  15.,  18.,  21.],
         [ 24.,  28.,  32.,  36.],
         [ 40.,  45.,  50.,  55.]],

        [[ 20.,  21.,  22.,  23.],
         [ 44.,  46.,  48.,  50.],
         [ 72.,  75.,  78.,  81.],
         [104., 108., 112., 116.],
         [140., 145., 150., 155.]]])

- 点积的计算
  - **注意**:torch.dot只能求一维向量的点积

In [152]:
y = torch.ones(4, dtype=torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

- 也可以执行元素乘法， 然后进行求和来表示两个向量的点积

In [153]:
torch.sum(x * y)

tensor(6.)

- 矩阵向量积Ax是一个长度为m的列向量， 其中$i^{th}$元素是点积$a_{i}^{T}x$

In [157]:
A = torch.arange(20,dtype=torch.float32).reshape(5, 4)
A.shape, x.shape, torch.mv(A, x)

(torch.Size([5, 4]), torch.Size([4]), tensor([ 14.,  38.,  62.,  86., 110.]))

- 矩阵矩阵乘法

In [ ]:
B = torch.ones((4, 3))
torch.mm(A, B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

- $L_2$范数是向量元素平方和的平方根
$$\|x\|_2 = \sqrt{\sum_{i=1}^{n}{x_i^2}}$$

In [159]:
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

- $L_1$范数是向量元素平方和的平方根
$$\|x\|_1 = \sum_{i=1}^{n}{|x_{i}|}$$

In [160]:
torch.abs(u).sum()

tensor(7.)

- 矩阵的F范数
$$\|X\|_F = \sqrt{\sum_{i=1}^{m}{\sum_{j=1}^{n}{x_{ij}^2}}}$$

In [161]:
torch.norm(torch.ones(4, 9))

tensor(6.)