## 访问元素
- 数组访问的时候切片访问格式是data[x:y:z]**(以一维数组为例)**
- 取的是索引$[x,y)$，**注意是左闭右开**区间的数值，**Z**是跳数，每z步取一次

In [4]:
import numpy as np
data = np.arange(12).reshape(3, 4)
print("data:")
print(data)
# 访问一个元素
print("Access 1 point")
print(data[1, 2])

# 访问一行
print("Access 1 line")
print(data[1, :])

# 访问一列
print("Access 1 column")
print(data[:, 1])

# 访问子区域
print("Access sub area")
print(data[1:3, 1:])

# 有跳数访问子区域
# 从头到尾，行上面每3跳取一次（中间隔两个），也就是0..2，列上面每2跳（中间隔一个）取一次，也就是0.1.2
print("Access sub area")
print(data[::3, ::2])

data:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Access 1 point
6
Access 1 line
[4 5 6 7]
Access 1 column
[1 5 9]
Access sub area
[[ 5  6  7]
 [ 9 10 11]]
Access sub area
[[0 2]]


## 数据操作
- 导入包
    - torch.arange(x), $[0,x)$的区间组成一个tensor

In [2]:
import torch
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

- 访问张量的形状和张量中元素的总数量**number of elements**

In [4]:
x.shape


torch.Size([12])

In [5]:
x.numel()

12

- 改变一个张量的形状而不改变它的元素值， 使用**reshape**函数

In [6]:
X = x.reshape(3, 4)
X 

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

- 创建全0，全1矩阵

In [8]:
torch.zeros((2, 3, 4))


tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [9]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

- 通过python列表来赋值

In [11]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])


tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [12]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]]).shape

torch.Size([3, 4])

- 其中标准的算术运算符$+, -, *, /, **$都可升级为按照元素计算

In [13]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

- 取指数运算

In [14]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

- 多个张量结合在一起
- **dim=0， 按行**拼接，**dim=1， 按列**拼接

In [ ]:
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

- 通过 **逻辑运算符**创建二元张量
  - 这里的二元指的是$0,1$矩阵

In [17]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

- 对张量中所有的元素进行求和会产生**只有一个元素**的张量， **是标量**

In [18]:
X.sum()

tensor(66.)

- 即使形状不同， 可以使用 **广播机制broadcasting mechanism**来执行按元素操作
  - 使用广播机制的时候， **维度必须一样**

In [19]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [20]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

- [-1]选择最后一个元素， [1:3]选择1，2行元素

In [21]:
X, X[-1], X[1:3]

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

- 通过索引将指定元素写入矩阵

In [22]:
X[1, 2] = 9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

- 为多个元素赋值相同的值， 我们只需要索引所有的元素， 然后为他们赋值

In [26]:
X[0:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

- 运行一些操作可能会导致为新结果分配内存
  - **id为变量在python中唯一的标识号**, 类似于C++中的指针
  - 不能一直复制一个变量，防止出现不必要的麻烦
  - 如果后面用不到Y了，那么前面Y的内存python会帮你自动释放，所以不需要特别担心内存的问题，符合编程规范就行了

In [30]:
before = id(Y)
Y = Y + X
id(Y) == before

False

In [32]:
before = id(Y)
Y[:, :] = Y + X
id(Y) == before

True

- 执行原地操作

In [33]:
Z = torch.zeros_like(Y)
print("id(Z): ", id(Z))
Z[:, :] = X + Y
print("id(Z): ", id(Z))

id(Z):  1766083040816
id(Z):  1766083040816


- 如果在后续计算中没有重复使用某一个张量X， 那么可以使用`X[:] = X + Y`或者`X += Y`等操作直接操作X， 防止不必要的内存开销
  - 像以下的操作中，如果直接操作X，就不会在内存中重新在内存中开辟一块空间给新的变量，有助于节省内存和显存

In [34]:
before = id(X)
X += Y
id(X) == before

True

- 转换为NumPy张量

In [35]:
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

- 可以将 **大小为1** 的Tensor转换为python标量

In [36]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

- 只有一个元素的tensor才能使用item()成员函数转成python标量

In [38]:
# X.item()

ValueError: only one element tensors can be converted to Python scalars

In [37]:
type(a), type(a.item()), type(float(a)), type(int(a))

(torch.Tensor, float, float, int)