## 访问元素
- 数组访问的时候切片访问格式是data[x:y:z]**(以一维数组为例)**
- 取的是索引$[x,y)$，**注意是左闭右开**区间的数值，**Z**是跳数，每z步取一次

In [1]:
import numpy as np
data = np.arange(12).reshape(3, 4)
print(data)
# 访问一个元素
print(data[1, 2])

# 访问一行
print(data[1, :])

# 访问一列
print(data[:, 1])

# 访问子区域
print(data[1:3, 1:])

# 有跳数访问子区域
# 从头到尾
print(data[::3, ::2])

[[0.72145137 0.9182353  0.61749645 0.67055156]
 [0.75923929 0.6168435  0.22437017 0.88791148]
 [0.79459197 0.40321026 0.40026363 0.95446631]]
