## 访问元素
- 数组访问的时候切片访问格式是data[x:y:z]**(以一维数组为例)**
- 取的是索引$[x,y)$，**注意是左闭右开**区间的数值，**Z**是跳数，每z步取一次

In [4]:
import numpy as np
data = np.arange(12).reshape(3, 4)
print("data:")
print(data)
# 访问一个元素
print("Access 1 point")
print(data[1, 2])

# 访问一行
print("Access 1 line")
print(data[1, :])

# 访问一列
print("Access 1 column")
print(data[:, 1])

# 访问子区域
print("Access sub area")
print(data[1:3, 1:])

# 有跳数访问子区域
# 从头到尾，行上面每3跳取一次（中间隔两个），也就是0..2，列上面每2跳（中间隔一个）取一次，也就是0.1.2
print("Access sub area")
print(data[::3, ::2])

data:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Access 1 point
6
Access 1 line
[4 5 6 7]
Access 1 column
[1 5 9]
Access sub area
[[ 5  6  7]
 [ 9 10 11]]
Access sub area
[[0 2]]
